const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=null,access='',showNewReceipt=false,syncBusy=false,lookupVersion=0;
const resultVersion=r=>JSON.stringify([r.id,r.status,r.note,r.published,r.documents]);
function message(text,error=false){const e=$('#message');e.hidden=false;e.className=error?'error':'success';e.textContent=text;}
async function api(url,data){return PPDBClient.request(url,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});}
function tab(name){for(const n of ['register','track']){$('#'+n+'-tab').setAttribute('aria-selected',String(n===name));}$('#registration').hidden=name!=='register';$('#tracking').hidden=name!=='track';$('#message').hidden=true;}
$('#register-tab').onclick=()=>tab('register');$('#track-tab').onclick=()=>tab('track');
for(const id of ['register-tab','track-tab'])$('#'+id).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'register':e.key==='End'?'track':id==='register-tab'?'track':'register';tab(next);$('#'+next+'-tab').focus();}};
function render(r,isNew=false){current=r;showNewReceipt=isNew;const docs=['Kartu keluarga','Akta kelahiran','Rapor'];$('#result').innerHTML=`<article class="receipt"><header><div><p class="eyebrow">BUKTI PENDAFTARAN · ${esc(r.year)}</p><h2>${esc(r.name)}</h2></div><span class="badge ${r.status==='Lulus'?'good':r.status==='Tidak lulus'?'bad':''}">${esc(r.status)}</span></header>${isNew?`<div class="code">Simpan nomor dan kode ini. Kode hanya ditampilkan saat pendaftaran.<strong>${esc(r.id)}</strong>Kode akses: <strong>${esc(access)}</strong></div>`:''}<dl>${[['Nomor pendaftaran',r.id],['NISN',r.nisn],['Asal sekolah',r.school],['Jalur',r.track],['Tanggal mendaftar',new Date(r.created).toLocaleDateString('id-ID')],['Nama wali',r.parent]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>${r.note?`<div class="notice">Catatan panitia: ${esc(r.note)}</div>`:''}<p>${r.published?'Hasil dan status di atas merupakan informasi terbaru dari panitia.':'Hasil kelulusan akan ditampilkan setelah pengumuman diterbitkan panitia.'}</p><div class="actions"><button class="secondary" id="refresh-result">Perbarui status</button><button class="secondary" id="print">Cetak bukti</button><button class="secondary" id="download">Simpan bukti .txt</button></div><p id="sync-status" class="muted small" role="status" aria-live="polite">Status diperbarui otomatis setiap 15 detik.</p><h3>Dokumen pendaftaran</h3><p class="muted small">PDF, JPG, atau PNG; maksimal 2 MB per berkas. Berkas dapat diganti sebelum diverifikasi.</p>${docs.map((kind,i)=>`<form class="upload-row" data-kind="${kind}"><label>${kind} <span class="badge ${r.documents.some(d=>d.kind===kind)?'good':''}">${r.documents.some(d=>d.kind===kind)?'Sudah diunggah':'Belum diunggah'}</span>${['Menunggu verifikasi','Perlu perbaikan'].includes(r.status)?`<input type="file" required accept=".pdf,.jpg,.jpeg,.png" aria-label="Unggah ${kind}" id="file-${i}">`:''}</label>${['Menunggu verifikasi','Perlu perbaikan'].includes(r.status)?'<button class="secondary">Unggah</button>':''}</form>`).join('')}</article>`;
$('#refresh-result').onclick=()=>refreshResult(true);$('#print').onclick=()=>window.print();$('#download').onclick=()=>{const a=document.createElement('a'),blob=new Blob([`BUKTI PENDAFTARAN SMP KATOLIK ST. YOSEPH LUWUK\nTahun: ${r.year}\nNama: ${r.name}\nNISN: ${r.nisn}\nNomor: ${r.id}\nKode akses (RAHASIA): ${access}\nStatus: ${r.status}\n\nBuka portal PPDB sekolah untuk memeriksa status terbaru.`],{type:'text/plain;charset=utf-8'});a.href=URL.createObjectURL(blob);a.download=r.id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
document.querySelectorAll('.upload-row').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button'),file=form.querySelector('input').files[0];if(!file||file.size>2097152)return message('Pilih berkas maksimal 2 MB.',true);btn.disabled=true;try{const content=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result.split(',')[1]);fr.onerror=()=>reject(Error('Berkas gagal dibaca.'));fr.readAsDataURL(file);});await api('/api/documents',{id:r.id,secret:access,kind:form.dataset.kind,content});render(await api('/api/results',{id:r.id,secret:access}),isNew);message('Dokumen berhasil disimpan.');}catch(e){message(e.message,true);}finally{btn.disabled=false;}});
}
$('#register-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,btn=form.querySelector('button'),data=Object.fromEntries(new FormData(form));data.consent=form.elements.consent.checked;btn.disabled=true;try{const r=await api('/api/applications',data);access=r.secret;tab('track');$('#track-form').elements.id.value=r.id;$('#track-form').elements.secret.value=access;render(r,true);form.reset();message('Pendaftaran berhasil. Simpan bukti beserta kode akses, lalu unggah tiga dokumen wajib.');}catch(e){message(e.message,true);}finally{btn.disabled=false;}};
$('#track-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));data.id=data.id.trim().toUpperCase();data.secret=data.secret.trim().toUpperCase();const btn=e.currentTarget.querySelector('button');btn.disabled=true;const version=++lookupVersion;current=null;access='';$('#result').innerHTML='';try{const r=await api('/api/results',data);if(version!==lookupVersion)return;access=data.secret;render(r);$('#message').hidden=true;}catch(e){message(e.message,true);}finally{btn.disabled=false;}};
api('/api/settings').then(s=>{const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Makassar'}),open=s.open&&(!s.start||today>=s.start)&&(!s.end||today<=s.end);$('#year').textContent='Tahun '+s.year;$('#open-status').textContent=open?'● Pendaftaran dibuka':'● Pendaftaran ditutup';$('#open-status').classList.toggle('good',open);$('#dates').textContent=s.start&&s.end?`${s.start} s.d. ${s.end}`:'Jadwal ditetapkan panitia';$('#requirements').textContent=s.requirements;$('#contact').textContent=s.contact;$('#registration-fields').disabled=!open;if(s.announcement){$('#announcement').hidden=false;$('#announcement').textContent=s.announcement;}if(!open){tab('track');}}).catch(e=>{$('#registration-fields').disabled=true;message('Informasi PPDB gagal dimuat. Muat ulang halaman. '+e.message,true);});

if(location.hash==='#hasil')tab('track');

// Refresh the authenticated receipt without persisting the student's access code.
async function refreshResult(manual=false){
 if(syncBusy||!current||!access||document.hidden||$('#tracking').hidden)return;
 // Keep a selected file intact until the student finishes uploading it.
 if([...document.querySelectorAll('.upload-row input[type=file]')].some(input=>input.files.length)||[...document.querySelectorAll('.upload-row button')].some(button=>button.disabled))return;
 const id=current.id,secret=access,version=lookupVersion;
 syncBusy=true;
 const button=$('#refresh-result');if(button)button.disabled=true;
 try{
   const next=await api('/api/results',{id,secret});
   if(!current||current.id!==id||access!==secret||lookupVersion!==version)return;
   if(resultVersion(current)!==resultVersion(next))render(next,showNewReceipt);
   const label=$('#sync-status');if(label)label.textContent='Tersinkron '+new Date().toLocaleTimeString('id-ID')+' · diperbarui otomatis setiap 15 detik.';
 }catch(error){
   if(current?.id===id&&lookupVersion===version){const label=$('#sync-status');if(label)label.textContent='Pembaruan belum berhasil. Status yang tampil adalah data terakhir. '+error.message;if(manual)message(error.message,true);}
 }finally{syncBusy=false;const button=$('#refresh-result');if(button)button.disabled=false;}
}
setInterval(()=>refreshResult(),15000);
window.addEventListener('focus',()=>refreshResult());
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshResult();});
