// Extend the admin with the same guarded CMS used by the public website.
window.SchoolAdmin = {
  async render() {
    const data = await api('/api/admin/school');
    if (view !== 'school') return;
    const p=data.profile;
    $('#content').innerHTML=`<div class="cms-heading"><div><h2>Konten website sekolah</h2><p class="muted">Kelola profil, berita, agenda, dan pengumuman yang ditampilkan di website.</p></div><button class="primary" id="new-post">+ Buat publikasi</button></div><section class="card card-body"><div class="cms-posts-head"><h3>Daftar publikasi</h3><span class="badge">${data.posts.length} konten</span></div><div class="table-wrap"><table><thead><tr><th>Judul</th><th>Kategori</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>${data.posts.map(p=>`<tr><td>${esc(p.title)}<small>${new Date(p.updated).toLocaleDateString('id-ID')}</small></td><td>${esc(p.type)}</td><td><span class="badge ${p.published?'good':''}">${p.published?'Terbit':'Draf'}</span></td><td><button class="secondary" data-post="${p.id}">Edit konten</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada publikasi. Buat berita, agenda, atau pengumuman pertama sekolah.</td></tr>'}</tbody></table></div></section><details class="card card-body profile-editor"><summary>Profil sekolah & tampilan beranda</summary><form id="school-profile"><div class="grid">${[['level','Jenjang / identitas',50],['name','Nama sekolah',100],['heroTitle','Judul utama beranda',120],['heroText','Deskripsi utama',400],['welcomeTitle','Judul sambutan',150],['address','Alamat sekolah',500],['email','Email sekolah (opsional)',180],['phone','Telepon sekolah (opsional)',25]].map(([k,label,max])=>`<label>${label}<input name="${k}" value="${esc(p[k])}" maxlength="${max}" ${['email','phone'].includes(k)?'':'required'} ${k==='email'?'type="email"':''}></label>`).join('')}</div><label>Sambutan / profil singkat<textarea name="welcomeText" required minlength="20" maxlength="5000" rows="7">${esc(p.welcomeText)}</textarea></label><label>Foto utama<select name="heroImage">${data.images.map((url,i)=>`<option value="${url}" ${url===p.heroImage?'selected':''}>${['Kebersamaan siswa','Gedung sekolah','Olahraga','Prestasi'][i]}</option>`).join('')}</select></label><button class="primary">Simpan profil sekolah</button></form></details>`;
    $('#new-post').onclick=()=>this.edit(null,data.images);
    document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>this.edit(data.posts.find(p=>p.id===Number(b.dataset.post)),data.images));
    $('#school-profile').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('/api/admin/school/profile',Object.fromEntries(new FormData(e.target)));message('Profil sekolah berhasil diperbarui.');}catch(error){message(error.message,true);}finally{button.disabled=false;}};
  },
  edit(post,images) {
    const p=post||{type:'Berita',title:'',summary:'',content:'',image:images[0],event_date:'',published:false};
    $('#detail .dialog-top h2').textContent=post?'Edit publikasi':'Publikasi baru';
    $('#detail-content').innerHTML=`<form id="post-form" class="post-form"><div class="grid"><label>Kategori<select name="type">${['Berita','Agenda','Pengumuman'].map(t=>`<option ${t===p.type?'selected':''}>${t}</option>`).join('')}</select></label><label id="event-date-label" ${p.type==='Agenda'?'':'hidden'}>Tanggal kegiatan<input type="date" name="event_date" value="${esc(p.event_date)}" ${p.type==='Agenda'?'required':''}></label></div><label>Judul<input name="title" value="${esc(p.title)}" required minlength="5" maxlength="160"></label><label>Ringkasan<textarea name="summary" required minlength="10" maxlength="350">${esc(p.summary)}</textarea></label><label>Isi publikasi<textarea name="content" required minlength="20" maxlength="15000" rows="10">${esc(p.content)}</textarea></label><label>Foto publikasi<select name="image">${images.map((url,i)=>`<option value="${url}" ${url===p.image?'selected':''}>${['Kebersamaan siswa','Gedung sekolah','Olahraga','Prestasi'][i]}</option>`).join('')}</select></label><label class="check"><input type="checkbox" name="published" ${p.published?'checked':''}><span>Terbitkan di website sekolah. Nonaktifkan untuk menyimpan sebagai draf.</span></label><p class="message" id="post-message" role="status" hidden></p><div class="actions"><button class="primary">Simpan publikasi</button>${post?.published?`<a class="secondary" href="/publikasi?id=${post.id}" target="_blank" rel="noopener">Lihat di website ↗</a>`:''}</div></form>`;
    const form=$('#post-form');
    form.elements.type.onchange=()=>{const event=form.elements.type.value==='Agenda';$('#event-date-label').hidden=!event;form.elements.event_date.required=event;};
    form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{const b=Object.fromEntries(new FormData(form));b.published=form.elements.published.checked;if(post)b.id=post.id;await api('/api/admin/school/posts',b);$('#detail').close();await load();message(b.published?'Publikasi berhasil diterbitkan.':'Draf berhasil disimpan.');}catch(error){$('#post-message').hidden=false;$('#post-message').textContent=error.message;}finally{button.disabled=false;}};
    $('#detail').showModal();
  }
};
