const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const scrypt=require('node:util').promisify(crypto.scrypt);
const {openDatabase}=require('./database');
const random=()=>crypto.randomBytes(24).toString('hex'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
async function passwordHash(p){const salt=random();return salt+':'+(await scrypt(p,salt,64)).toString('hex');}
async function match(p,stored){const [salt,key]=stored.split(':');return crypto.timingSafeEqual(Buffer.from(key,'hex'),await scrypt(p,salt,64));}
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function str(b,k,min=1,max=200){if(typeof b[k]!=='string'||b[k].trim().length<min||b[k].trim().length>max)fail('Isian '+k+' tidak valid.');return b[k].trim();}
function credentials(b){const c={name:str(b,'name',2,100),email:str(b,'email',5,150).toLowerCase(),password:str(b,'password',12,128)};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email))fail('Email tidak valid.');return c;}

async function createApp(db){
await db.initialize();
const transaction=fn=>db.transaction(fn);
(await db.prepare('INSERT INTO settings VALUES(1,?) ON DUPLICATE KEY UPDATE id=id').run(JSON.stringify({year:'2026/2027',open:false,start:'',end:'',published:false,announcement:'',requirements:'Kartu keluarga, akta kelahiran, dan rapor terakhir.',contact:'Hubungi panitia di sekolah untuk informasi biaya dan bantuan.'})));
const settings=async()=>JSON.parse((await db.prepare('SELECT data FROM settings WHERE id=1').get()).data);
async function audit(actor,action){await db.prepare('INSERT INTO audit(actor,action,created) VALUES(?,?,?)').run(actor,action,new Date().toISOString());}
const buckets=new Map();function limit(req,group,max=20,consume=true){const k=req.socket.remoteAddress+group,now=Date.now();let b=buckets.get(k);if(!b||b.until<now)b={count:0,until:now+900000};buckets.set(k,b);if((consume?++b.count:b.count)>max)fail('Terlalu banyak percobaan. Coba lagi dalam 15 menit.',429);}
const cleanup=setInterval(async()=>{for(const [k,v] of buckets)if(v.until<Date.now())buckets.delete(k);try{(await db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now()));}catch(e){console.error('Session cleanup:',e.code);}},60000).unref();
async function body(req){if(!req.headers['content-type']?.startsWith('application/json'))fail('Gunakan JSON.',415);let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>3000000)fail('Berkas terlalu besar.',413);chunks.push(c);}try{const b=JSON.parse(Buffer.concat(chunks).toString());if(!b||typeof b!=='object'||Array.isArray(b))fail('Data tidak valid.');return b;}catch{fail('Data tidak valid.');}}
async function session(req,mutation=false,superOnly=false){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ppdb_session='))?.slice(13);const s=(await db.prepare('SELECT sessions.*,admins.name,admins.email,admins.role,admins.approved FROM sessions JOIN admins ON admins.id=sessions.admin_id WHERE token=? AND expires>?').get(hash(token||''),Date.now()));if(!s||!s.approved)fail('Silakan login admin.',401);if(mutation&&req.headers['x-csrf-token']!==s.csrf)fail('Sesi keamanan tidak valid. Muat ulang halaman.',403);if(superOnly&&s.role!=='superadmin')fail('Tindakan ini hanya untuk superadmin.',403);return s;}
const isPublished=async year=>Boolean((await db.prepare('SELECT published FROM result_publications WHERE year=?').get(year))?.published);
const finalStatuses=['Lulus','Tidak lulus','Cadangan'];
async function application(r,admin=false){const published=await isPublished(r.year),hidden=!admin&&!published&&finalStatuses.includes(r.status);return {id:r.id,nisn:r.nisn,year:r.year,...JSON.parse(r.data),status:hidden?'Seleksi berlangsung':r.status,...(admin?{studentStatus:!published&&finalStatuses.includes(r.status)?'Seleksi berlangsung':r.status}:{}),note:hidden?'':r.note,created:r.created,published,documents:(await db.prepare('SELECT id,kind FROM documents WHERE application_id=?').all(r.id))};}
async function applicant(b,lock=false){const r=(await db.prepare('SELECT * FROM applications WHERE id=? AND secret=?'+(lock?' FOR UPDATE':'')).get(str(b,'id'),hash(str(b,'secret'))));if(!r)fail('Nomor pendaftaran atau kode akses tidak sesuai.',404);return r;}
function validDate(d){return typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;}
const schoolCMS=await require('./school-cms')(db,{session,body,fail,str,audit,transaction});
const server=http.createServer(async(req,res)=>{
const json=(v,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(v));};
res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
try{const p=new URL(req.url,'http://localhost').pathname,m=req.method;
if(p.startsWith('/api/')){
res.setHeader('Cache-Control','no-store');
if(!['GET','HEAD'].includes(m)){const expected=process.env.APP_ORIGIN||`http://${req.headers.host}`;if(req.headers.origin&&req.headers.origin!==expected||req.headers['sec-fetch-site']==='cross-site')fail('Asal permintaan ditolak.',403);}
if(p==='/api/health'&&m==='GET'){res.setHeader('Access-Control-Allow-Origin','*');await db.prepare('SELECT 1').get();return json({service:'st-yoseph-ppdb',version:1});}
if(await schoolCMS(req,res,p,m,json))return;
if(p==='/api/settings'&&m==='GET')return json(await settings());
if(p==='/api/admin/register'&&m==='POST'){limit(req,'register',8);const c=credentials(await body(req)),pw=await passwordHash(c.password);try{(await db.prepare('INSERT INTO admins(name,email,password) VALUES(?,?,?)').run(c.name,c.email,pw));}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;}return json({message:'Permintaan diproses. Akun baru menunggu persetujuan superadmin.'},201);}
if(p==='/api/admin/login'&&m==='POST'){limit(req,'login',15);const b=await body(req),email=str(b,'email',1,150).toLowerCase(),pw=str(b,'password',1,128),a=(await db.prepare('SELECT * FROM admins WHERE email=?').get(email));const ok=await match(pw,a?.password||'0'.repeat(48)+':'+'0'.repeat(128));if(!a||!ok||!a.approved)fail('Login gagal atau akun belum disetujui.',401);const token=random(),csrf=random();(await db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hash(token),a.id,csrf,Date.now()+28800000));res.setHeader('Set-Cookie',`ppdb_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);await audit(a.email,'Login');return json({name:a.name,role:a.role,csrf});}
if(p==='/api/admin/me'&&m==='GET'){const s=await session(req);return json({name:s.name,role:s.role,csrf:s.csrf});}
if(p==='/api/admin/logout'&&m==='POST'){const s=await session(req,true);(await db.prepare('DELETE FROM sessions WHERE token=?').run(s.token));res.setHeader('Set-Cookie','ppdb_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json({ok:true});}
if(p==='/api/applications'&&m==='POST'){limit(req,'apply',10);const b=await body(req),s=await settings(),today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Makassar'});if(!s.open||(s.start&&today<s.start)||(s.end&&today>s.end))fail('Pendaftaran belum dibuka atau sudah ditutup.',409);const data={};for(const [k,min,max] of [['name',2,120],['birthPlace',2,100],['birthDate',10,10],['gender',1,20],['school',2,150],['address',10,500],['parent',2,120],['phone',8,20],['email',5,150],['track',2,30]])data[k]=str(b,k,min,max);const nisn=str(b,'nisn',10,10);if(!/^\d{10}$/.test(nisn))fail('NISN harus 10 digit.');if(!/^\+?\d{8,15}$/.test(data.phone))fail('Nomor telepon tidak valid.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))fail('Email tidak valid.');if(!['Laki-laki','Perempuan'].includes(data.gender)||!['Reguler','Prestasi','Afirmasi'].includes(data.track))fail('Pilihan tidak valid.');if(!validDate(data.birthDate)||data.birthDate>=today||data.birthDate<'1990-01-01')fail('Tanggal lahir tidak valid.');if(b.consent!==true)fail('Persetujuan pengolahan data diperlukan.');data.consentAt=new Date().toISOString();const id='PPDB-'+crypto.randomBytes(6).toString('hex').toUpperCase(),secret=crypto.randomBytes(12).toString('hex').toUpperCase();try{(await db.prepare('INSERT INTO applications(id,nisn,year,secret,data,created) VALUES(?,?,?,?,?,?)').run(id,nisn,s.year,hash(secret),JSON.stringify(data),new Date().toISOString()));}catch(e){if(e.code==='ER_DUP_ENTRY')fail('NISN sudah terdaftar pada tahun ajaran ini.',409);throw e;}return json({...await application((await db.prepare('SELECT * FROM applications WHERE id=?').get(id))),secret},201);}
if(p==='/api/results'&&m==='POST'){limit(req,'lookup',30,false);const input=await body(req);let row;try{row=await applicant(input);}catch(error){limit(req,'lookup',30);throw error;}return json(await application(row));}
if(p==='/api/documents'&&m==='POST'){return json(await transaction(async()=>{limit(req,'upload',30);const b=await body(req),r=await applicant(b,true);if(!['Menunggu verifikasi','Perlu perbaikan'].includes(r.status))fail('Berkas sudah dikunci panitia.',409);if(!['Kartu keluarga','Akta kelahiran','Rapor'].includes(b.kind))fail('Jenis dokumen tidak valid.');if(typeof b.content!=='string'||!b.content.length||b.content.length>2800000||!/^[A-Za-z0-9+/]*={0,2}$/.test(b.content))fail('Berkas maksimal 2 MB.');const data=Buffer.from(b.content,'base64');if(data.length>2097152)fail('Berkas maksimal 2 MB.');let mime='';if(data.subarray(0,5).toString()==='%PDF-')mime='application/pdf';if(data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))mime='image/png';if(data[0]===255&&data[1]===216&&data[2]===255)mime='image/jpeg';if(!mime)fail('Gunakan PDF, JPG, atau PNG yang valid.');(await db.prepare('INSERT INTO documents VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE mime=VALUES(mime),content=VALUES(content)').run(random(),r.id,b.kind,mime,data));return {ok:true};}));}
if(p.startsWith('/api/admin/')){const s=await session(req,m!=='GET');
if(p==='/api/admin/applications'&&m==='GET')return json(await Promise.all((await db.prepare('SELECT * FROM applications ORDER BY created DESC').all()).map(r=>application(r,true))));
if(p==='/api/admin/decision'&&m==='POST'){return json(await transaction(async()=>{const b=await body(req),id=str(b,'id'),status=str(b,'status'),note=typeof b.note==='string'?b.note.trim():'';if(note.length>1000)fail('Catatan maksimal 1000 karakter.');if(!['Menunggu verifikasi','Perlu perbaikan','Terverifikasi',...finalStatuses].includes(status))fail('Status tidak valid.');const r=(await db.prepare('SELECT * FROM applications WHERE id=? FOR UPDATE').get(id));if(!r)fail('Pendaftar tidak ditemukan.',404);if(s.role!=='superadmin'&&(finalStatuses.includes(status)||finalStatuses.includes(r.status)))fail('Penetapan seleksi hanya oleh superadmin.',403);if(['Terverifikasi','Lulus','Cadangan'].includes(status)&&(await db.prepare('SELECT COUNT(*) AS n FROM documents WHERE application_id=?').get(id)).n<3)fail('Tiga dokumen wajib harus lengkap.');await transaction(async()=>{(await db.prepare('UPDATE applications SET status=?,note=? WHERE id=?').run(status,note,id));await audit(s.email,`${id}: ${r.status} → ${status}`);});return {ok:true};}));}
if(p==='/api/admin/settings'&&m==='POST'){await session(req,true,true);const b=await body(req),next={year:str(b,'year',9,9),open:b.open===true,published:b.published===true,start:b.start||'',end:b.end||'',announcement:typeof b.announcement==='string'?b.announcement.slice(0,2000):'',requirements:str(b,'requirements',1,2000),contact:str(b,'contact',1,1000)};if(!/^\d{4}\/\d{4}$/.test(next.year))fail('Tahun ajaran harus berbentuk 2026/2027.');for(const d of [next.start,next.end])if(d&&!validDate(d))fail('Tanggal tidak valid.');if(next.start&&next.end&&next.start>next.end)fail('Tanggal akhir harus setelah tanggal mulai.');await transaction(async()=>{(await db.prepare('INSERT INTO result_publications VALUES(?,?) ON DUPLICATE KEY UPDATE published=VALUES(published)').run(next.year,next.published?1:0));(await db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(next)));await audit(s.email,'Mengubah pengaturan PPDB dan publikasi '+next.year);});return json(next);}
if(p==='/api/admin/accounts'&&m==='GET'){await session(req,false,true);return json((await db.prepare('SELECT id,name,email,role,approved FROM admins ORDER BY id').all()));}
if(p==='/api/admin/accounts'&&m==='POST'){await session(req,true,true);const b=await body(req),target=(await db.prepare('SELECT * FROM admins WHERE id=?').get(Number(b.id)));if(!target||target.role==='superadmin')fail('Akun tidak dapat diubah.');await transaction(async()=>{(await db.prepare('UPDATE admins SET approved=? WHERE id=?').run(b.approved===true?1:0,target.id));(await db.prepare('DELETE FROM sessions WHERE admin_id=?').run(target.id));await audit(s.email,`Akses ${target.email}: ${b.approved===true?'aktif':'nonaktif'}`);});return json({ok:true});}
if(p==='/api/admin/audit'&&m==='GET'){await session(req,false,true);return json((await db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 200').all()));}
if(p.startsWith('/api/admin/documents/')&&m==='GET'){const d=(await db.prepare('SELECT * FROM documents WHERE id=?').get(p.split('/').pop()));if(!d)fail('Dokumen tidak ditemukan.',404);res.writeHead(200,{'Content-Type':d.mime,'Content-Disposition':`attachment; filename="${d.kind.replaceAll(' ','-')}.${d.mime==='application/pdf'?'pdf':d.mime==='image/png'?'png':'jpg'}"`});return res.end(Buffer.from(d.content));}}
fail('Endpoint tidak ditemukan.',404);}
if(m!=='GET'&&m!=='HEAD')fail('Metode tidak diizinkan.',405);const routes={'/':'index.html','/ppdb':'ppdb.html','/admin':'admin.html','/publikasi':'publication.html'},file=routes[p]||p.slice(1);if(!['index.html','style.css','script.js','ppdb.html','admin.html','ppdb.css','ppdb.js','admin.js','school.js','api-client.js','school.css','school-admin.js','publication.html'].includes(file)&&!/^assets\/school\/[a-zA-Z0-9_-]+\.(jpg|png|jpeg|svg|webp)$/.test(file))fail('Halaman tidak ditemukan.',404);const full=path.join(__dirname,file);if(!fs.existsSync(full))fail('Halaman tidak ditemukan.',404);const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});if(m==='HEAD')return res.end();fs.createReadStream(full).pipe(res);
}catch(e){if(!e.status)console.error(e);if(!res.headersSent)json({error:e.status?e.message:'Terjadi kesalahan server. Silakan coba kembali.'},e.status||500);else res.end();}});
return {server,db,close:async()=>{clearInterval(cleanup);if(server.listening)await new Promise((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await db.close();}};
}
async function start(){
  const db=await openDatabase();let app;
  try{
    app=await createApp(db);
    if(process.argv.includes('--create-admin')){
      const c=credentials({name:process.env.ADMIN_NAME||'Superadmin',email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
      if(await db.prepare('SELECT id FROM admins WHERE email=?').get(c.email))throw new Error('Email sudah ada.');
      await db.prepare("INSERT INTO admins(name,email,password,role,approved) VALUES(?,?,?,'superadmin',1)").run(c.name,c.email,await passwordHash(c.password));
      console.log('Superadmin berhasil dibuat.');await app.close();return;
    }
    await new Promise((resolve,reject)=>{app.server.once('error',reject);app.server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',resolve);});
    console.log('PPDB MySQL: http://'+(process.env.HOST||'127.0.0.1')+':'+(process.env.PORT||3000)+'/ppdb | Admin: /admin');
    for(const signal of ['SIGINT','SIGTERM'])process.once(signal,()=>app.close().catch(e=>{console.error(e.code||e.message);process.exitCode=1;}));
  }catch(e){if(app)await app.close();else await db.close();throw e;}
}
if(require.main===module)start().catch(e=>{console.error('PPDB gagal dimulai:',e.code||e.message);console.error('Pastikan MySQL XAMPP aktif, database tersedia, dan konfigurasi .env benar.');process.exitCode=1;});
module.exports={createApp,passwordHash};
