const {test,after,before}=require('node:test');
const assert=require('node:assert/strict');
const {testDatabase}=require('./mysql-helper');
const {createApp,passwordHash}=require('../server');let app,server,db,fixture,base,cookie,csrf,operatorCookie,operatorCsrf,id,secret;
async function req(p,data,auth=false,override={}){const headers={'Content-Type':'application/json',...(auth?{cookie,'X-CSRF-Token':csrf}:{}),...override};const r=await fetch(base+p,{method:data?'POST':'GET',headers,...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,body:await r.json(),headers:r.headers};}
before(async()=>{fixture=await testDatabase();db=fixture.db;app=await createApp(db);server=app.server;await db.prepare("INSERT INTO admins(name,email,password,role,approved) VALUES(?,?,?,'superadmin',1)").run('Admin','admin@example.test',await passwordHash('Testing-password-123!'));await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{if(app)await app.close();if(fixture)await fixture.cleanup();});
test('PPDB registration, authorization, documents and publication lifecycle',async()=>{
 assert.equal((await req('/api/admin/applications')).status,401);
 for(const p of ['/server.js','/data/ppdb.sqlite','/.git/config','/README.md','/.env','/database.js','/database/schema.sql','/scripts/migrate-sqlite.js'])assert.equal((await fetch(base+p)).status,404);
 for(const p of ['/','/ppdb','/admin','/ppdb.css','/ppdb.js','/admin.js','/school.js','/school.css','/school-admin.js','/publikasi'])assert.equal((await fetch(base+p)).status,200);
 let r=await req('/api/admin/login',{email:'admin@example.test',password:'Testing-password-123!'});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];csrf=r.body.csrf;assert.match(r.headers.get('set-cookie'),/HttpOnly/);
 const config={...(await req('/api/settings')).body,open:true};
 assert.equal((await req('/api/admin/settings',config,true,{'X-CSRF-Token':'wrong'})).status,403);
 assert.equal((await req('/api/admin/settings',config,true,{origin:'https://evil.test'})).status,403);
 const student={name:'Siswa Pengujian',nisn:'1234567890',birthPlace:'Luwuk',birthDate:'2014-02-03',gender:'Perempuan',school:'SD Pengujian',address:'Jalan Pengujian nomor 12',parent:'Orang Tua',phone:'081234567890',email:'wali@example.test',track:'Reguler',consent:true};
 assert.equal((await req('/api/applications',student)).status,409);
 assert.equal((await req('/api/admin/settings',config,true)).status,200);
 assert.equal((await req('/api/applications',{...student,birthDate:'2014-02-31'})).status,400);
 r=await req('/api/applications',student);assert.equal(r.status,201);({id,secret}=r.body);assert.ok(secret);assert.equal((await req('/api/applications',student)).status,409);
 assert.equal((await req('/api/results',{id,secret:'incorrect'})).status,404);
 assert.equal((await req('/api/admin/decision',{id,status:'Lulus'},true)).status,400);
 assert.equal((await req('/api/documents',{id,secret,kind:'Rapor',content:Buffer.from('<script>bad</script>').toString('base64')})).status,400);
 for(const kind of ['Kartu keluarga','Akta kelahiran','Rapor'])assert.equal((await req('/api/documents',{id,secret,kind,content:Buffer.from('%PDF-1.4\nTest fixture').toString('base64')})).status,200);
 const largeDocument=Buffer.alloc(2097152,42);largeDocument.write('%PDF-1.4');
 assert.equal((await req('/api/documents',{id,secret,kind:'Rapor',content:largeDocument.toString('base64')})).status,200);
 const largeId=(await req('/api/results',{id,secret})).body.documents.find(d=>d.kind==='Rapor').id;
 const largeDownload=await fetch(base+'/api/admin/documents/'+largeId,{headers:{cookie}});
 assert.deepEqual(Buffer.from(await largeDownload.arrayBuffer()),largeDocument);
 assert.equal((await req('/api/documents',{id,secret,kind:'Rapor',content:Buffer.concat([largeDocument,Buffer.from('x')]).toString('base64')})).status,400);
 r=await req('/api/results',{id,secret});assert.equal(r.body.documents.length,3);assert.equal(r.body.secret,undefined);
 assert.equal((await req('/api/admin/documents/'+r.body.documents[0].id)).status,401);
 const download=await fetch(base+'/api/admin/documents/'+r.body.documents[0].id,{headers:{cookie}});assert.equal(download.status,200);assert.match(download.headers.get('content-disposition'),/attachment/);
 assert.equal((await req('/api/admin/register',{name:'Operator',email:'operator@example.test',password:'Operator-password-123!'})).status,201);
 assert.equal((await req('/api/admin/login',{email:'operator@example.test',password:'Operator-password-123!'})).status,401);
 const accounts=(await req('/api/admin/accounts',null,true)).body,operator=accounts.find(a=>a.role==='operator');
 assert.equal((await req('/api/admin/accounts',{id:operator.id,approved:true},true)).status,200);
 r=await req('/api/admin/login',{email:'operator@example.test',password:'Operator-password-123!'});operatorCookie=r.headers.get('set-cookie').split(';')[0];operatorCsrf=r.body.csrf;
 const op={cookie:operatorCookie,'X-CSRF-Token':operatorCsrf};
 assert.equal((await req('/api/admin/school',null,false,op)).status,403);
 assert.equal((await req('/api/admin/school/posts',{title:'Unauthorized'},false,op)).status,403);
 assert.equal((await req('/api/admin/settings',config,false,op)).status,403);
 assert.equal((await req('/api/admin/accounts',null,false,op)).status,403);
 assert.equal((await req('/api/admin/decision',{id,status:'Lulus'},false,op)).status,403);
 assert.equal((await req('/api/admin/decision',{id,status:'Terverifikasi'},false,op)).status,200);
 assert.equal((await req('/api/admin/decision',{id,status:'Lulus',note:'Selamat bergabung.'},true)).status,200);
 r=await req('/api/results',{id,secret});assert.equal(r.body.status,'Seleksi berlangsung');assert.equal(r.body.note,'');assert.equal(r.body.studentStatus,undefined);
 const adminRow=(await req('/api/admin/applications',null,true)).body.find(a=>a.id===id);assert.equal(adminRow.status,'Lulus');assert.equal(adminRow.studentStatus,'Seleksi berlangsung');assert.equal(adminRow.published,false);
 for(let i=0;i<35;i++)assert.equal((await req('/api/results',{id,secret})).status,200,'Valid status refresh must not exhaust login-attempt limits');
 assert.equal((await req('/api/admin/decision',{id,status:'Terverifikasi'},false,op)).status,403);
 assert.equal((await req('/api/admin/settings',{...config,published:true},true)).status,200);
 r=await req('/api/results',{id,secret});assert.equal(r.body.status,'Lulus');assert.equal(r.body.note,'Selamat bergabung.');assert.equal(r.body.published,true);const publishedRow=(await req('/api/admin/applications',null,true)).body.find(a=>a.id===id);assert.equal(publishedRow.studentStatus,r.body.status);
 assert.equal((await req('/api/documents',{id,secret,kind:'Rapor',content:'eA=='})).status,409);
 assert.equal((await req('/api/admin/accounts',{id:operator.id,approved:false},true)).status,200);
 assert.equal((await req('/api/admin/applications',null,false,op)).status,401);
 assert.ok((await req('/api/admin/audit',null,true)).body.length>=5);
 assert.equal((await req('/api/admin/logout',{},true)).status,200);
 assert.equal((await req('/api/admin/applications',null,true)).status,401);
});


test('School CMS: guarded editing, drafts, publication, dates and year isolation',async()=>{
 let r=await req('/api/admin/login',{email:'admin@example.test',password:'Testing-password-123!'});
 cookie=r.headers.get('set-cookie').split(';')[0];csrf=r.body.csrf;
 assert.equal((await req('/api/admin/school')).status,401);
 const initial=(await req('/api/school')).body;
 assert.equal(initial.posts.length,0);
 const payload={type:'Berita',title:'Kabar sekolah pengujian',summary:'Ringkasan untuk pengujian publikasi.',content:'Informasi kegiatan sekolah untuk pengujian penyimpanan konten.',image:'/assets/school/siswa.jpg',published:false};
 assert.equal((await req('/api/admin/school/posts',payload,true,{'X-CSRF-Token':'invalid'})).status,403);
 assert.equal((await req('/api/admin/school/posts',{...payload,image:'https://evil.test/image.svg'},true)).status,400);
 assert.equal((await req('/api/admin/school/posts',{...payload,type:'Agenda',event_date:'2026-02-30'},true)).status,400);
 r=await req('/api/admin/school/posts',payload,true);assert.equal(r.status,201);const postId=r.body.id;
 assert.equal((await req('/api/school')).body.posts.length,0);
 assert.equal((await req('/api/school/posts/'+postId)).status,404);
 assert.equal((await req('/api/admin/school/posts',{...payload,id:postId,published:true},true)).status,200);
 r=await req('/api/school/posts/'+postId);assert.equal(r.body.post.title,payload.title);
 assert.equal((await req('/api/school')).body.posts.length,1);
 assert.equal((await req('/api/admin/school/posts',{...payload,id:postId,published:false},true)).status,200);
 assert.equal((await req('/api/school/posts/'+postId)).status,404);
 const profile={...initial.profile,heroTitle:'Sekolah untuk masa depan siswa.'};
 assert.equal((await req('/api/admin/school/profile',profile,true)).status,200);
 assert.equal((await req('/api/school')).body.profile.heroTitle,profile.heroTitle);
 assert.equal((await req('/api/admin/school/profile',{...profile,email:'invalid'},true)).status,400);
 const conf=(await req('/api/settings')).body;
 // Closing publication for a new school year must not hide the previous cohort.
 assert.equal((await req('/api/admin/settings',{...conf,year:'2027/2028',published:false},true)).status,200);
 assert.equal((await req('/api/results',{id,secret})).body.status,'Lulus');
 // The original cohort can still be unpublished explicitly.
 assert.equal((await req('/api/admin/settings',{...conf,published:false},true)).status,200);
 assert.equal((await req('/api/results',{id,secret})).body.status,'Seleksi berlangsung');
 assert.ok((await db.prepare('SELECT COUNT(*) AS n FROM school_posts').get()).n>0);
});
